import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useAccount } from 'wagmi';
import { useState } from 'react';
import { Alchemy, GetBaseNftsForOwnerOptions, Network, OwnedNftsResponse } from 'alchemy-sdk';

const Home: NextPage = () => {

  const { address } = useAccount();
  const [enterAddress, setEnterAddress] = useState("");
  const [nftDetails, setNftDetails] = useState<OwnedNftsResponse>();
  const [noOfNftsFetched, setNoOfNftsFetched] = useState(0);
  const [dataFetched, setDataFetched] = useState(false);

  const config = {
    apiKey: "SgFPh5gQUCimLa1Vam8ZocKrmMwd3_V-",
    network: Network.ETH_MAINNET,
  };

  const alchemy = new Alchemy(config);

  async function fetchNfts() {
    let owner = "idrt.eth";
    // let options : GetBaseNftsForOwnerOptions = {
    //   pageSize: 10,
    //   omitMetadata: true
    // };
    let response = await alchemy.nft.getNftsForOwner(enterAddress); //"idrt.eth"
    setNftDetails(response);
    setDataFetched(true);
    setNoOfNftsFetched(response.totalCount);
    console.log("RESPONSE" + response);
  };


  // async function fetchData() {
  //   try {
  //     if (enterAddress != null) {
  //       const networkInfo = {
  //         network: ZDKNetwork.Ethereum,
  //         chain: ZDKChain.Mainnet,
  //       }

  //       const API_ENDPOINT = "https://api.zora.co/graphql";
  //       const zdk = new ZDK({ endpoint: API_ENDPOINT });

  //       // for specific NFT
  //       // const args = {
  //       //   token: {
  //       //     // networks:[networkInfo],
  //       //     address: "0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb",
  //       //     tokenId: "101"
  //       //   },
  //       //   includeFullDetails: false 
  //       // }0xA858DDc0445d8131daC4d1DE01f834ffcbA52Ef1

  //       const args = {
  //         where: {
  //           ownerAddresses: [enterAddress] //0xA858DDc0445d8131daC4d1DE01f834ffcbA52Ef1 
  //         },
  //         pagination: { limit: 10 },
  //       };

  //       const response = await zdk.tokens(args);
  //       //array containing info about the nfts

  //       setNftDetails(response);
  //       if (response.tokens.nodes != null) {
  //         setDataFetched(true);
  //       }

  //       if (nftDetails != null) {
  //         nftDetails.tokens.nodes.map((element) => {
  //           console.log(element.token.tokenContract?.name?.toString());
  //         });
  //       }
  //     }
  //   } catch (error) {
  //     console.error("Exception {}", error);
  //   }
  // }

  function showNfts() {

    if (dataFetched) {
      if (noOfNftsFetched > 0 && nftDetails != null) {
        return (
          <div className="grid grid-cols-4">
            {
              nftDetails.ownedNfts.map((element) => {
                if (element.title.length > 0) {
                  return (
                    <div className="flex-col items-center justify-center mx-10 my-10 text-lg box-border max-w-sm rounded overflow-hidden shadow-lg">
                      <img className="w-full h-60" src={element.media.at(0)?.gateway} alt="displaying the nft" />
                      <div className="px-6 py-4">
                        <div className="font-bold text-xl mb-2">{element.title}</div>
                      </div>
                    </div>
                  )
                }

              })
            }
          </div>
        )
      }
      else {
        return (
          <div>
            <p>Sorry there are no NFTs owned by this address currently, in the meantime have a look at our minions NFT</p>
            <div className="grid grid-cols-4">
              <div className="flex-col items-center justify-center mx-10 my-10 text-lg box-border max-w-sm rounded overflow-hidden shadow-lg">
                <img className="w-full h-60" src="https://cdn.wallpapersafari.com/54/55/fTKnpB.jpg" alt="displaying the nft" />
                <div className="px-6 py-4">
                  <div className="font-bold text-xl mb-2">Minions</div>
                </div>
              </div>
            </div>
          </div>
        )
      }
    }
  }

  return (
    <div>
      <Head>
        <title>All About NFTs</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="All About NFTs"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main>
        <nav className="px-4 py-3 bg-black text-white flex justify-end fixed w-full top-0">
          <ul className="pl-28 py-1 flex space-x-11">
            <ConnectButton accountStatus={"avatar"} showBalance={false} chainStatus={"none"} />
          </ul>
        </nav>
      </main>

      <p className='pt-[15vh]'>Hello</p>
      <input className='width:10px' placeholder='Enter address' onChange={(e) => setEnterAddress(e.target.value)} />
      <button onClick={fetchNfts}>FETCH</button>

      {showNfts()}

      <footer className={styles.footer}>
        <a>
          Made by Sabhani Bros.
        </a>
      </footer>
    </div>
  );
};

export default Home;

